CONFIG_LOG=y
CONFIG_LOG_BUFFER_SIZE=16384
CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=10
CONFIG_LOG_PROCESS_TRIGGER_THRESHOLD=1
CONFIG_LOG_BACKEND_UART_BUFFER_SIZE=128
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_KSCAN_LOG_LEVEL_DBG=y
