CONFIG_ZMK_POINTING=y
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_2NDIDEAL_STATUS_LED=y
#CONFIG_ZMK_2NDIDEAL_STATUS_LED_TEST=y
#CONFIG_ZMK_2NDIDEAL_STATUS_LED_TEST_DELAY_MS=20
CONFIG_ZMK_TINCAN=y
CONFIG_NANOPB=y
#CONFIG_ZMK_KSCAN_MATRIX_POLLING=y
#CONFIG_ZMK_KSCAN_DIRECT_POLLING=y
CONFIG_LED_STRIP_INIT_PRIORITY=80
